version: "3.8"
services:
  db_postgres:
    image: postgres:16.2-bookworm
    env_file:
      - .env.docker
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - intranet
    ports:
      - "5434:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 10s
      retries: 3

  fastapi:
    build: .
    env_file:
      - .env.docker
    restart: unless-stopped
    ports:
      - "${REST_PORT}:${REST_PORT}"
    networks:
      - intranet
    depends_on:
      db_postgres:
        condition: service_healthy

networks:
  intranet:
    external: false
